### ISSUE TITLE
Quest marker updates flatline the game.

### ISSUE THREAD

**Issue by WhiteElf** [jackhumbert/in_world_navigation#12]
I have noticed that we a quest marker trail updates due to walking through a door for instance, the game will flatline immediately, without any errors.
This happens when the quest marker is on the doorway to exit a location.  You walk through the doorway and the quest marker now changes to the next exit or its proper destination and the game flatlines.
Uninstall the mod and the problem goes away on the same save.  Reinstall the mod and the issue comes back.

**Comment by Thortok** [comment]
Make sure you have the latest version. There was a crash issue in the first version.

If you're sure it's the latest version having the issue, then upload a save file right before the crash happens.

**Comment by WhiteElf** [comment]
Latest version straight from Github releases.
I'll give it a go on a new save just to make sure it is not any other mods.

**Comment by WhiteElf** [comment]
Hmmm, it seems when this mod is used on its own, it works fine.  I can add Cyber Engine Tweaks along with your mid and it also works fine.  As soon as any other mods are added, the flatlining comes back.  I think there will be a CET update not far off, so you may want to hold till then.  This was all done with a new fresh game.

**Comment by Thortok** [comment]
More than likely it's the mod you're adding that's causing the flatline, not this mod.

I am running a ton of mods and I don't flatline.

CET
No Intro videos
Untrack Quest
Now playing
Inventory maid
redscript
Muted markers
AlmostAutoLoot
AutoHeal
Auto Component Upgrade
Improved Radio
Eye Adaptation Auto exposure fix
red4ext
skip main menu
always first equip
purify the UI
sensible stamina and athletics
adaptive graphics quality
autohide iconic blueprint
state based attributes
native settings ui
HUD fixes
track what you want
in world navigation
notifications for radio song changes

A couple that aren't showing in my vortex list like "let there be flight" as well as the dependencies for that one and 'in world navigation'

**Comment by WhiteElf** [comment]
For reference, looks like the issue was with a mod called 'E3 Compass'.  I'll stick with using my compass mod instead.  The E3 mod doesn't look like it is being developed anymore.  I might dig into their code later and fix it again when I have time.  Closing this case.
