### ISSUE TITLE
Latest hotfix breaks mod

### ISSUE THREAD

**Issue by flyryan** [jackhumbert/in_world_navigation#29]
This mod fails to compile with redscript on launch after today's hotfix patch. ~~May be related to jackhumbert/mod_settings#12~~

**Comment by flyryan** [comment]
Just updating to confirm that the mod is still broken, even with the resolution of 
jackhumbert/mod_settings#12 (thanks for that update btw!).

**Comment by Oomwoc** [comment]
I can also verify that this mod currently is not working.
