### ISSUE TITLE
Game crash on specific quest events

### ISSUE THREAD

**Issue by Thortok** [jackhumbert/in_world_navigation#3]
Editing to consolidate known locations:

Gimme danger - After choosing to go with Goro to do reconnaissance
Gimme danger - After leaning on balcony and V says "better get comfortable"
Never Fade Away - Right after choosing whether or not to take drugs in Johnny's flashback
Gig: Bloodsport - At the end, after talking to Roh, if you did NOT complete using stealth (completing with stealth didn't crash)
Gig: Freedom of the Press - At the end, when Regina is about to give optional objective for convincing Max
The Hunt - After finding cartoon and talking to Joss, accepting to stay the night
Violence - After talking to Lizzy and you get up to go
The Beast in Me - Talking to Claire at start, quest transitions to waiting a day for response
Search and Destroy - After checking door and returning to Takamura
Search and Destroy - Leaving the building (without rescuing Takamura)
I'll Fly Away - When you get to the bridge
Kold Mirage - When told to put the deck on the counter
Chippin' In - right when you take the pill at the Afterlife
Chippin' In - after getting the tattoo
Following the River - when you get near the location

**Comment by Thortok** [comment]
Similar crash later in the quest. After leaning on balcony and scanning anything, V says "better get comfortable"

Seems what's happening here is the full-screen glitch-cut effect to indicate passage of time and space.

**Comment by Thortok** [comment]
Another crash in the "Never Fade Away" quest (Johnny flashback where you meet Alt)

**Comment by Thortok** [comment]
Another crash in Gig: Bloodsport, at the end, right after talking to Roh.

**Comment by Thortok** [comment]
Another crash in Gig: Freedom of the Press, right at the end, when Regina is about to give you the optional objective to collect a bonus reward (if you earned it). Same spot as in Bloodsport basically.

**Comment by Thortok** [comment]
Another crash in the quest "The Hunt" - after finding the cartoon and talking to Joss, accepting to stay results in crash.

**Comment by Thortok** [comment]
The quest Violence, after talking to Lizzy and you get up to go, game crashes.

**Comment by Thortok** [comment]
Just did Bloodsport WITH the optional objective, and no crash. So on that one it crashes if you don't stealth.

**Comment by Thortok** [comment]
The quest "The Beast in Me" when you first talk to Claire and the quest is about to transition to waiting a day...another crash.

**Comment by Thortok** [comment]
So I tried untracking the quest right before that moment happened and the game didn't crash. This may be a temporary workaround.

**Comment by Thortok** [comment]
The 'untracking' method worked for "The Beast in Me" quest but did NOT work for the "Never Fade Away" flashback. Even though I was spamming the untrack button lol

Unless you say otherwise I plan to keep reporting any/every instance of crashing and the specific locations. It's your mod but personally I'd say it's probably the bug of biggest concern to deal with first since people can't play a game that keeps crashing.

**Comment by Thortok** [comment]
Quest "Search and Destroy" after checking the noise at the door there's a quick 'return to Takamura' objective before you get blown in the hole. And then game crashes. Untracking after the return to Takamura objective appears prevents crash.

**Comment by Thortok** [comment]
And another crash in "Search and Destroy" the second you step outside the building (didn't rescue Takamura)

**Comment by Thortok** [comment]
Quest "I'll Fly Away" when following mitch and you get to the bridge, crashes.

**Comment by Thortok** [comment]
Quest "Kold Mirage" when told to put the deck on the counter ginger-like

**Comment by Thortok** [comment]
Quest "Chippin' In" right when you take the pill at the afterlife

**Comment by Thortok** [comment]
Quest "Chippin' In" crashes after getting the tattoo even if you untracked the quest

**Comment by Thortok** [comment]
Quest "Following the River" when you get near the location

**Comment by jackhumbert** [comment]
I think I have a fix ready - should be up soon :)

**Comment by Thortok** [comment]
Sweet, ready to test it asap ^_^

**Comment by jackhumbert** [comment]
Just pushed the fix - you can download the [`build/` folder](https://github.com/jackhumbert/in_world_navigation/tree/main/build) and install things from there if you'd like to test. It auto-closed the issue, but if it persists, feel free to reopen :)

**Comment by Thortok** [comment]
Tried the 'Violence' one and it crashed in the same spot, so, not fixed. =(

**Comment by Thortok** [comment]
Wait, I see the Main.cpp file is updated...but I'm not sure where to put this as I didn't have this file before.

**Comment by Thortok** [comment]
I'm also unable to reopen the issue, or at least I can't figure out how to.

**Comment by jackhumbert** [comment]
[Here's a link to download the specific folder](https://downgit.github.io/#/home?url=https://github.com/jackhumbert/in_world_navigation/tree/main/build) - you can install it the same way you did initially. There shouldn't be any Main.cpp :)

**Comment by Thortok** [comment]
On nexusmods someone has made the conclusion that this seems to happen when a "scripted autosave" happens, such as during a cutscene. Automatic regular-interval autosaves don't seem to trigger the crash.

Starting a new list of crashes confirmed to occur with the version you posted:

Violence - after talking to Lizzy and getting up to go

**Comment by jackhumbert** [comment]
The fix I pushed last night checks for the gameplay tier, and only runs the update when it's Tier3_LimitedGameplay or lower, thus avoiding the cinematic scenes - maybe it needs to be Tier2_StagedGameplay, or only Tier1_FullGameplay? Did you notice any reduction in crashes with the change?

**Comment by Thortok** [comment]
Haven't tested long enough to check, plan to play all day today so will report what I find

**Comment by jackhumbert** [comment]
I just pushed an update that limits the path update to full gameplay, and turns it off for others - shouldn't crash, but if you notice the path not showing up where it'd be useful, we can experiment with the other tiers.

**Comment by Thortok** [comment]
Confirming that it did not crash at a previous spot, which was in The Hunt, standing up to go to sleep. But almost immediately after, when putting on the BD headset, it crashed then, lol

**Comment by jackhumbert** [comment]
Would you be able to zip up your gamesave right before that point? Struggling to find a way to get to these quests without playing through the whole game :)

**Comment by Thortok** [comment]
[AutoSave-19.zip](https://github.com/jackhumbert/in_world_navigation/files/8884322/AutoSave-19.zip)

Not sure this is IMMEDIATELY before but it's just a little bit before, should be pretty close

**Comment by Thortok** [comment]
Going forward I will post a save file for any other crashes I come across

**Comment by Thortok** [comment]
[QuickSave-4.zip](https://github.com/jackhumbert/in_world_navigation/files/8884449/QuickSave-4.zip)

Full Disclosure, after talking to Sandra in her apartment

**Comment by Thortok** [comment]
[AutoSave-16.zip](https://github.com/jackhumbert/in_world_navigation/files/8884503/AutoSave-16.zip)

Crash at The Hunt braindance, better save file, right in front of it.

**Comment by jackhumbert** [comment]
Just pushed a possible fix (b678de7) - instead of checking the gameplay tier, I'm just checking the pointer value that's actually causing the crash haha. Seems to work with cinematic & braindance events.

**Comment by Thortok** [comment]
Confirming Hunt braindance is fixed

**Comment by Thortok** [comment]
[AutoSave-17.zip](https://github.com/jackhumbert/in_world_navigation/files/8884623/AutoSave-17.zip)

The Hunt quest, after doing all the braindances, getting to the barn, disabling security, getting inside, River asks you to turn off a machine, and then you go back to River, and it crashes there. For whatever reason saving is blocked during all of this so this save is the closest I can get to that point.

**Comment by jackhumbert** [comment]
Just pushed a fix - this should handle all situations :)

**Comment by Thortok** [comment]
Confirming "I'll Fly Away" is fixed

**Comment by Thortok** [comment]
Confirming Kold Mirage (put deck on counter) is fixed

**Comment by Thortok** [comment]
Confirming Chippin' In is fixed

**Comment by Thortok** [comment]
Confirming Following the River is fixed. I think you licked it. Not gonna spam any more, I think this is a release candidate for nexusmods.
